config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'pages#home'
  get "about" => "pages#about" # creates the about_path

  match '/soon', to: 'pages#soon', via: 'get'
  match '/chapter01', to: 'pages#chapter01', via: 'get'
  match '/chapter02', to: 'pages#chapter02', via: 'get'
  match '/chapter03', to: 'pages#chapter03', via: 'get'
  match '/chapter04', to: 'pages#chapter04', via: 'get'
  match '/chapter05', to: 'pages#chapter05', via: 'get'
  match '/chapter06', to: 'pages#chapter06', via: 'get'
  match '/chapter07', to: 'pages#chapter07', via: 'get'
  match '/chapter08', to: 'pages#chapter08', via: 'get'
  match '/chapter09', to: 'pages#chapter09', via: 'get'

  match '/chapter10', to: 'pages#chapter10', via: 'get'
  match '/chapter11', to: 'pages#chapter11', via: 'get'
  
  match '/test', to: 'pages#test', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

  def soon
  end

  def chapter01
  end

  def chapter02
  end

  def chapter03
  end

  def chapter04
  end

  def chapter05
  end

  def chapter06
  end

  def chapter07
  end

  def chapter08
  end

  def chapter09
  end

  def chapter10
  end

  def chapter11
  end


  def test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_benefits_section.html.erb
	<!-- **** Second Content Section **** -->
	<div class="container top-space bottom-space side-space benefits-bg">
		<div class="row">
			<div class="col-md-6 col-sm-12 highlight">
				
				<div class="h-caption center">
					<i class="glyphicon glyphicon-flash icon-page-home"></i>
					<h3>Accelerated Learning</h3>
				</div>
				<div class="h-body center">
					<p>We believe pictures and interactivity will enchance learning, so thats how we desgin our lectures! Our practice page after each lecture allows you to test your knowledge on what was just learned through a drag and drop interactions.</p> 
				</div>
			</div>

			<div class="col-md-6 col-sm-12 highlight">
				<div class="h-caption center">
					<i class="glyphicon glyphicon-user icon-page-home"></i>
					<h3>Student Focused</h3>
				</div>
				<div class="h-body center">
					<p>Studies have shown that students learn most effectively when they teach eachother. Our content is centered around this fact, our lessons are created by students. Our language is straight to the point and jargonless.</p>
				</div>
			</div>


		</div>
	</div>

app/views/layouts/_footer.html.erb
	<!-- **** Footer **** -->
	<footer class="text-center">
		<div class="footer-above">
			<div class="container">
				<div class="row">
					<div class="footer-col col-md-4">
						<h3>Contact Us</h3>
						<p>270 Mohegan Ave<br>
							 New London, CT 06320
						</p>
					</div>
					<div class="footer-col col-md-4">
						<h3>Follow Us</h3>
						<ul class="footer-links">
							<li><%= link_to "Facebook", 'https://www.facebook.com/orgodojo', class: "footer-links" %></li>
							<li><%= link_to "Twitter", '#', class: "footer-links" %></li>
						</ul>
					</div>

					<div class="footer-col col-md-4">
						<h3>About Us</h3>
						<p>We provide content created<br>
							 by students for students.
						</p>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-below">
			<div class="container">
				<div class="row">
					<div class="col-md-12">&copy; 2014 OrgoDojo</div>
				</div>
			</div>
		</div>
	</footer>

app/views/layouts/_footer_above.html.erb
	<!-- **** Footer - Above **** -->
	<footer class="text-center">
		<div class="footer-above">
			<div class="container">
				<div class="row">
					<div class="footer-col col-md-4">
						<h3>About Us</h3>
						<p>We are a NYC-based startup that provides resources created by students for students.</p>
					</div>
					<div class="footer-col col-md-4">
						<h3>Follow Us</h3>
						<ul class="footer-links">
							<li><%= link_to "Facebook", 'https://www.facebook.com/orgodojo', class: "footer-links" %></li>
						</ul>
					</div>
					<div class="footer-col col-md-4">
						<h3>Contact Us</h3>
						<p>Forward all compliments, or complaints, to tektekpush@gmail.com</p>
					</div>

				</div>
			</div>
		</div>
	</footer>

app/views/layouts/_footer_below.html.erb
	<!-- **** Footer - Below **** -->
	<footer class="text-center">
		<div class="footer-below">
			<div class="container">
				<div class="row">
					<div class="col-md-12">&copy; 2015 OrgoDojo</div>
				</div>
			</div>
		</div>
	</footer>

app/views/layouts/_header.html.erb
  


  <!-- **** Navigation Bar  **** -->

  <nav class="navbar navbar-default navbar-static-top navbar-page-home" role="navigation">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "OrgoDojo", root_path, class: "navbar-brand brand-page-home" %>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right links-page-home">
          <li><%= link_to "Begin", chapter01_path %></li>
        </ul>

        
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>

app/views/layouts/_tracker.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53716612-1', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');

</script>

app/views/layouts/_welcome_section.html.erb
	

	<!-- **** First Content Section **** -->		
	<div class="welcome-section">



			<div class="welcome-desc">
				<h1 class="title">WELCOME</h1>
				<div>
					<div class="subtext">Discover lectures to master organic chemistry concepts</div>
				</div>
					<p>
		      	<!-- Later this this will say "Enroll Now for Only $14.99" -->
		        <%= link_to "Get Started", chapter01_path , class: "btn btn-default btn-lg btn-welcome" %>
		      </p>
			</div>	

	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OrgoDojo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0">  mobile device configuration -->
  <meta name="google-site-verification" content="nHjJXEblJ658tiaQFEVzfChT9Hnnws78nFy8gz00XNQ" />
  <%= render 'layouts/tracker' %>
</head>
<body>

	<%= yield %>
	<%= render 'layouts/footer_below' %>


</body>
</html>

app/views/pages/_disqus.html.erb
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'orgodojo'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    

app/views/pages/_disqus_board.html.erb
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'orgodojo'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    

app/views/pages/about.html.erb
<h1> About Us at OrgoDojo! </h1>
<p>Here is the company information.</p>

app/views/pages/chapter02.html.erb
<%= render 'pages/chapters_header' %>


<div class="container text-color">
	<div class="row">
		
		<div class="col-md-10 col-sm-12">
			<h1 class="center"> Chapter 2 - Alkanes</h1>


				<div class="panel-group">
				  <div class="panel panel-default">
				    <div class="panel-heading" data-toggle="collapse" href="#collapseOne">
				      <h4 class="panel-title">
				        <a>
				          Alkanes: Hydrocarbon Molecules
				        </a>
				      </h4>
				    </div>


				    <div id="collapseOne" class="panel-collapse collapse in">
				      <div class="panel-body">
				        <p>• Hydrocarbons are molecules that only contain carbon and hydrogen bonds. Below are some examples.<br>
								<%= image_tag "ch201-alkanes.png", size: "480x90", class: "center-img" %>
								•	Each molecule fits into a functional group category that is listed below the name.<br>
								•	Molecules names are generated based on their functional class.<br>

								</p>
				      </div>
				    </div>
				  </div>


				  <div class="panel panel-default">
				    <div class="panel-heading">
				      <h4 class="panel-title" data-toggle="collapse" href="#collapseTwo">
				        <a>
				          Alkanes and Isomers
				        </a>
				      </h4>
				    </div>


				    <div id="collapseTwo" class="panel-collapse collapse">
				      <div class="panel-body">
				        <p>• Alkanes can be drawn in straight chains or in branched chains, if long enough.<br>
								• The many different branched alkanes generated are called constitutional isomers.
								<%= image_tag "ch202-isomers.png", size: "280x120", class: "center-img" %>

								•	The molecular formula for each isomer is the same (C4H10) but the connectivity is different.<br>
								•	Alkanes that are missing a hydrogen to be complete have the –yl ending.<br>
								•	Alkyl groups are substituent groups. Below we can see methyl is a substituent of the R compound (R represents any compound).<br>
								<%= image_tag "ch203-methane and methyl.png", size: "220x80", class: "center-img" %>
								</p>
				      </div>
				    </div>
				  </div>


				  <div class="panel panel-default">
				    <div class="panel-heading">
				      <h4 class="panel-title" data-toggle="collapse" href="#collapseThree">
				        <a>
				          Nomenclature
				        </a>
				      </h4>
				    </div>

				    <div id="collapseThree" class="panel-collapse collapse">
				      <div class="panel-body">
								<p>• Follow these rules to name these molecules.<br>
								•	Step 1: Identify the longest continuous carbon chain<br>
								•	Step 2: All other carbons will be substituents that end in –yl<br>
								•	Step 3: Number the chain in the direction that gives the slowest substituent position<br>
								•	Step 4: Write the name formula: alkyl pos. + alkyl name + continuous chain name<br>
								
								<%= image_tag "ch204-nomenclature.png", size: "200x140", class: "center-img" %>

								</p>
				      </div>
				    </div>
				  </div>


				  <div class="panel panel-default">
				    <div class="panel-heading">
				      <h4 class="panel-title" data-toggle="collapse" href="#collapseFour">
				        <a>
				          Chemical Properties of Alkanes
				        </a>
				      </h4>
				    </div>

				    <div id="collapseFour" class="panel-collapse collapse">
				      <div class="panel-body">
								<p>• Alkanes are generally unreactive and often used as solvents for you reactants.<br>
								</p>
				      </div>
				    </div>
				  </div>


				  <div class="panel panel-default">
				    <div class="panel-heading">
				      <h4 class="panel-title" data-toggle="collapse" href="#collapseFive">
				        <a>
				          Physical Properties of Alkanes
				        </a>
				      </h4>
				    </div>

				    <div id="collapseFive" class="panel-collapse collapse">
				      <div class="panel-body">
								<p>• Alkanes have low melting points.<br>
								• Alkanes also have low boiling points.<br>
								•	Soluble in nonpolar solvents due to weak induced dipole intermolecular forces (the “like dissolves like” concept).<br>
								•	Branched alkanes have lower boiling points than linear alkanes because they have less surface area available for intermolecular force (IMF) interactions. Less stacking results in weaker IMFs holding the molecules together in phase.<br>
								</p>
				      </div>
				    </div>
				  </div>


				  <div class="panel panel-default">
				    <div class="panel-heading">
				      <h4 class="panel-title" data-toggle="collapse" href="#collapseSix">
				        <a>
				          Stability of Alkanes
				        </a>
				      </h4>
				    </div>

				    <div id="collapseSix" class="panel-collapse collapse">
				      <div class="panel-body">
								<p>• Branched alkane isomers are more stable than the linear isomers.<br>
								•	Alkanes are stable molecules.
								</p>
				      </div>
				    </div>
				  </div>


				  <div class="panel panel-default">
				    <div class="panel-heading">
				      <h4 class="panel-title" data-toggle="collapse" href="#collapseSeven">
				        <a>
				          Heat of Combustion
				        </a>
				      </h4>
				    </div>

				    <div id="collapseSeven" class="panel-collapse collapse">
				      <div class="panel-body">
								<p>• Branched alkanes expend less energy than linear alkanes when subjected to combustion due to their stability.
								</p>
				      </div>
				    </div>
				  </div>


				</div>

		</div>

		<div class="col-md-2 col-sm-12 container-adsbygoogle">
			
			<div class="">
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- page-chapter02#1 -->
				<ins class="adsbygoogle ad-sidebar"
				     style="display:block;width:250px;height:225px"
				     data-ad-client="ca-pub-7111029893672600"
				     data-ad-slot="7582799577"></ins>
				<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script>
			</div>

			<div class="hidden-xs">
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- page-chapter02#2 -->
				<ins class="adsbygoogle ad-sidebar"
				     style="display:block;width:250px;height:225px"
				     data-ad-client="ca-pub-7111029893672600"
				     data-ad-slot="4489732370"></ins>
				<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script>
			</div>

		</div>

	</div>
	<ul class="pager">
	  <li class="previous">
	  	<%= link_to "Back", chapter01_path , class: "text-left" %>
	  </li>
	  <li class="next">
	  	<%= link_to "Next", chapter03_path, class: "text-right" %>
	  </li>
	</ul>

	<%= render 'pages/disqus_board' %>
</div>

app/views/pages/chapter10.html.erb
<%= render 'pages/chapters_header' %>



	<div class="container text-color">
		<div class="row">
			<div class="col-md-12">
			<h1 class="center"> Chapter 10 - Conjugated Systems</h1>


			<div class="panel-group">

			  <div class="panel panel-default">
			    <div class="panel-heading" data-toggle="collapse" href="#collapseOne">
			      <h4 class="panel-title">
			        <a>
			          Overview
			        </a>
			      </h4>
			    </div>


			    <div id="collapseOne" class="panel-collapse collapse in">
			      <div class="panel-body">
			        <p>
			        	<%= image_tag "ch1001-overview.png", size: "200x130", class: "center-img" %>
			        	•	Conjugated systems offer resonance stablized intermediates. They can be fully conjugated or isolated.<br>
			        	•	Above we have two systems with conjugation. The second compound has isolated conjugation.<br>
			        	•	The arrows point to the allylic position which has an array of synthetic utility.
			        </p>
			      </div>
			    </div>
			  </div>

			  <div class="panel panel-default">
			    <div class="panel-heading" data-toggle="collapse" href="#collapseTwo">
			      <h4 class="panel-title">
			        <a>
			        	Allylic Resonance
			        </a>
			      </h4>
			    </div>


			    <div id="collapseTwo" class="panel-collapse collapse">
			      <div class="panel-body">
			        <p>
			        	
			        	<%= image_tag "ch1002-allyl-resonance.png", size:"360x80", class: "center-img" %>
			        	<h4 class="emphasis">Overview</h4>
								•	Allyl compounds are great to work with because they're intermediates are resonance stabilized.<br>
								•	The cationic charge is stabilized by the adjacent electron-donating carbon-carbon double bond group.	
			        </p>
			      </div>
			    </div>
			  </div>

			  <div class="panel panel-default">
			    <div class="panel-heading" data-toggle="collapse" href="#collapseThree">
			      <h4 class="panel-title">
			        <a>
			          Nucleophilic Substitutions
			        </a>
			      </h4>
			    </div>


			    <div id="collapseThree" class="panel-collapse collapse">
			      <div class="panel-body">
			        <p>
			        	<%= image_tag "ch1003-allyl-sn1.png", size: "", class: "center-img" %>
			        	<h4 class="emphasis">Overview</h4>
			        	•	Allyl groups can be used as part of S<sub>N</sub>1 reactions.<br>
			        	<%= image_tag "ch1004-allyl-sn2.png", size: "", class: "center-img" %>
			        	<h4 class="emphasis">Overview</h4>
			        	•	If there is an allylic leaving group at the primary position then an S<sub>N</sub>2 reactions can occur.
			        </p>
			      </div>
			    </div>
			  </div>


			  <div class="panel panel-default">
			    <div class="panel-heading" data-toggle="collapse" href="#collapseFour">
			      <h4 class="panel-title">
			        <a>
								Allylic Bromination
			        </a>
			      </h4>
			    </div>


			    <div id="collapseFour" class="panel-collapse collapse">
			      <div class="panel-body">
			        <p>
			        	<%= image_tag "ch1005-NBS-reaction.png", size: "285x115", class: "center-img" %>
			        	<h4 class="emphasis">Overview</h4>
								•	This is a great free-radical reaction for the bromination of alkenes at the allylic position. The mechanism involves the use of electrophilic bromine.
								<%= image_tag "ch1006-br2-allylic.png", size: "300x65", class: "center-img" %>
			        	<h4 class="emphasis">Overview</h4>
			        	•	This is a great free-radical reaction for the bromination of alkenes at the allylic position. The mechanism involves the use of electrophilic bromine.


			        </p>
			      </div>
			    </div>
			  </div>



			  <div class="panel panel-default">
			    <div class="panel-heading" data-toggle="collapse" href="#collapseFive">
			      <h4 class="panel-title">
			        <a>
			          Dienes
			        </a>
			      </h4>
			    </div>


			    <div id="collapseFive" class="panel-collapse collapse">
			      <div class="panel-body">
			        <p>
			        	<%= image_tag "ch1007-prep-diene.png", size: "285x80", class: "center-img" %>
			        	<h4 class="emphasis">Overview</h4>
								•	Dehydration of alkyl halides or alcohol compound with a double bond already present will generate a conjugated diene. Conjugated dienes are preferred over isolated dienes because there are more stable.
			        	
			        </p>
			      </div>
			    </div>
			  </div>



			  <div class="panel panel-default">
			    <div class="panel-heading" data-toggle="collapse" href="#collapseSix">
			      <h4 class="panel-title">
			        <a>
			          Thermodynamics and Kinetics
			        </a>
			      </h4>
			    </div>


			    <div id="collapseSix" class="panel-collapse collapse">
			      <div class="panel-body">
			        <p>
			        	<%= image_tag "ch1008-HBr-heat-allylic.png", size: "355x65", class: "center-img" %>
			        	<h4 class="emphasis">Overview</h4>
			        	•	When addition reactions of dienes are conducted in high temperature conditions 1,4 addition occurs. These reactions are said to be under thermodynamic control and yields a thermodynamically stable product.

			        	<%= image_tag "ch1009-HBr-cold-allylic.png", size: "325x70", class: "center-img" %>
			        	<h4 class="emphasis">Overview</h4>
			        	•	Low temperature reaction conditions for dienes result in 1,2 addition products. These reactions are controlled by kinetics: the reaction occurs via the fastest route.


			        </p>
			      </div>
			    </div>
			  </div>



			  <div class="panel panel-default">
			    <div class="panel-heading" data-toggle="collapse" href="#collapseSeven">
			      <h4 class="panel-title">
			        <a>
			          Diels-Alder Reaction
			        </a>
			      </h4>
			    </div>


			    <div id="collapseSeven" class="panel-collapse collapse">
			      <div class="panel-body">
			        <p>
			        	<%= image_tag "ch1010-diels-alder.png", size: "430x150", class: "center-img" %>
			        	<h4 class="emphasis">Overview</h4>
			        	•	This is a great reaction for the synthesis of ring structures. The reaction requires a diene, a dienophile, and heat.<br>
								•	The endo product is the major compound produced. This occurs because the diene positions itself over the dienophile during the reaction.<br>
								<%= image_tag "ch1011-dienes-dienophiles.png", size: "450x250", class: "center-img" %>
								•	These are a couple of the dienes and dienophiles that you might encounter in your course. 

								<!-- Add HOMO/LUMO Pictures -->




			        </p>
			      </div>
			    </div>
			  </div>




			</div>






		</div>
		<ul class="pager">
		  <li class="previous">
		  	<%= link_to "Back", chapter09_path, class: "text-left" %>
		  </li>
		  <li class="next">
		  	<%= link_to "Next", soon_path, class: "text-right" %>
		  </li>
		</ul>
		<%= render 'pages/disqus_board' %>
	</div>

app/views/pages/home.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/welcome_section' %>
<%= render 'layouts/benefits_section' %>
<%= render 'layouts/footer_above' %>

app/views/pages/soon.html.erb
<%= render 'pages/chapters_header' %>


<div class="jumbotron text-color">
	<div class="container center">
	  <h2>Chapter 11 and Much More Coming Soon!</h2>
	  <div class="container">
			<ul class="pager">
			  <li class="previous">
			  	<%= link_to "Back", chapter10_path, class: "text-left" %>
			  </li>
			  <li class="next">
			  	<%= link_to "Home", root_path, class: "text-left" %>
			  </li>
			</ul>
		</div>
	</div>
</div>